---
title: CV
name: Lory
surname: Salazar
position: "Master's Candidate"
address: "Bren School of Environmental Science & Management"
phone: (702) 445-4187
www: linkedin.com/in/llsv/
email: "lls@ucsb.edu"
github: lorysalazar
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "Lory is a first-year master's student studying Conservation Planning at the Bren School of Environmental Science & Management."
output: 
  vitae::markdowncv:
    theme: kjhealy
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

## Skills and Interests

 * I volunteered with lions and other animals at the Lion Habitat Zoo
 * I am bilingual in English and Spanish
 * I have a certification in graphic design and illustration

## Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Master of Environmental Science & Management", "Expected June 2022", "Bren School of Environmental Science and Management - University of California, Santa Barbara (UCSB)", "Santa Barbara, CA",
  "Bachelor of Science in Biological Sciences", "2019", "University of Nevada, Las Vegas", "Las Vegas, NV"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

## Professional Experience

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  2020, "Creative Marketing Assistant, Sable Systems International", "Examined biotechology market and presented 10+ analyses to CEO, composed and edited copy in Microsoft Office, directed and edited 5+ videos using Adobe Premiere Pro",
  2018, "Marketing Intern, Sable Systems International", "Maintained and updated research publication database, updated technology inventory of 50+ prodcts, surveyed competitor market segments"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

